import { useState } from 'react';
import { View, Pressable } from 'react-native';

import Text from '@/components/ui/Text';
import Icon from '@/components/icons/Icon';
import { useTheme } from '@/theme/useTheme';

// ---------------------------------------------------------------------------
// Static policy notice shown above the AI tab of the Projects grid. Play's
// Generative AI content policy expects this kind of disclosure to sit
// alongside AI output, not just at the moment it was generated — so it stays
// collapsible but reappears on every visit rather than a one-time dismiss.
// ---------------------------------------------------------------------------
export default function AiPolicyCard({ onContactSupport }) {
  const { colors, radius } = useTheme();
  const [expanded, setExpanded] = useState(false);

  return (
    <View style={{ marginBottom: 16 }}>
      <Pressable
        onPress={() => setExpanded((v) => !v)}
        style={({ pressed }) => ({
          flexDirection: 'row',
          alignItems: 'center',
          gap: 14,
          padding: 16,
          borderRadius: radius.xl,
          backgroundColor: colors.surface,
          borderWidth: 1,
          borderColor: colors.lineSoft,
          opacity: pressed ? 0.85 : 1,
        })}
      >
        <View
          style={{
            width: 44,
            height: 44,
            borderRadius: radius.md,
            backgroundColor: colors.accentSoft,
            alignItems: 'center',
            justifyContent: 'center',
          }}
        >
          <Icon name="shield" size={21} color={colors.accent} strokeWidth={1.9} />
        </View>
        <View style={{ flex: 1 }}>
          <Text variant="titleSm">AI-Generated Content Policy</Text>
          <Text variant="bodySm" color="ink3" style={{ marginTop: 2 }}>
            What you should know before using an AI design
          </Text>
        </View>
        <Icon name={expanded ? 'chevron-up' : 'chevron-down'} size={16} color={colors.ink3} strokeWidth={2} />
      </Pressable>

      {expanded ? (
        <View
          style={{
            marginTop: 8,
            padding: 16,
            borderRadius: radius.md,
            backgroundColor: colors.surface2,
            borderWidth: 1,
            borderColor: colors.lineSoft,
          }}
        >
          <Text variant="bodySm" color="ink2" style={{ lineHeight: 20 }}>
            Designs generated by AI are a starting point, not a guarantee — you're responsible for
            how you use them. They shouldn't be used for anything requiring copyright clearance,
            structural accuracy, or safety compliance. If a design looks off or inappropriate, use
            Report on the card, or{' '}
            <Text
              variant="bodySm"
              color="accent"
              style={{ fontWeight: '700' }}
              onPress={onContactSupport}
            >
              contact support
            </Text>
            .
          </Text>
        </View>
      ) : null}
    </View>
  );
}
