import { captureRef } from 'react-native-view-shot';
import * as MediaLibrary from 'expo-media-library';
import * as Sharing from 'expo-sharing';
import * as Print from 'expo-print';
import * as FileSystem from 'expo-file-system';

import { planArea } from '@/domain/floorplan';
import { formatLength } from '@/domain/units';

// Capture a view ref to PNG and save it to the photo library (with permission),
// falling back to the share sheet.
export async function exportPng(viewRef, filename = 'homeplanner') {
  const uri = await captureRef(viewRef, { format: 'png', quality: 1 });
  try {
    const perm = await MediaLibrary.requestPermissionsAsync();
    if (perm.granted) {
      await MediaLibrary.saveToLibraryAsync(uri);
      return { uri, saved: true };
    }
  } catch {
    /* fall through to sharing */
  }
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: 'image/png' });
  }
  return { uri, saved: false, filename };
}

// Build a dimensioned PDF of the plan via HTML → print-to-PDF, then share it.
export async function exportPdf(project) {
  const { plan, name } = project;
  const html = `
    <html><body style="font-family: -apple-system, sans-serif; padding:32px; color:#1B1A17;">
      <h1 style="color:#BC5B3A;">${name}</h1>
      <p style="color:#57534B;">Floor plan · ${plan.width.toFixed(1)}m × ${plan.length.toFixed(1)}m · ${planArea(plan)} m²</p>
      <div style="border:3px solid #BC5B3A; border-radius:8px; width:${plan.width * 60}px; height:${plan.length * 60}px; position:relative; margin-top:24px; background:#FBF6F1;">
        <div style="position:absolute; top:-24px; left:0; right:0; text-align:center; color:#A44E30;">${formatLength(plan.width)}</div>
        <div style="position:absolute; left:-70px; top:50%; color:#A44E30;">${formatLength(plan.length)}</div>
      </div>
      <p style="margin-top:40px; color:#9A9488;">Generated by HomePlanner</p>
    </body></html>`;
  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: 'application/pdf' });
  }
  return { uri };
}

// Generate a minimal OBJ (floor + wall boxes + furniture boxes) and share it.
export async function exportObj(project) {
  const obj = buildObj(project.plan);
  const uri = `${FileSystem.cacheDirectory}${project.name.replace(/\s+/g, '_')}.obj`;
  await FileSystem.writeAsStringAsync(uri, obj);
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: 'model/obj' });
  }
  return { uri };
}

// --- OBJ geometry builder -------------------------------------------------
function buildObj(plan) {
  let out = '# HomePlanner export\n';
  let vCount = 0;

  const box = (cx, cy, cz, w, d, h) => {
    const x0 = cx - w / 2;
    const x1 = cx + w / 2;
    const y0 = cz;
    const y1 = cz + h;
    const z0 = cy - d / 2;
    const z1 = cy + d / 2;
    const verts = [
      [x0, y0, z0],
      [x1, y0, z0],
      [x1, y0, z1],
      [x0, y0, z1],
      [x0, y1, z0],
      [x1, y1, z0],
      [x1, y1, z1],
      [x0, y1, z1],
    ];
    verts.forEach((v) => {
      out += `v ${v[0].toFixed(3)} ${v[1].toFixed(3)} ${v[2].toFixed(3)}\n`;
    });
    const f = (a, b, c, d2) =>
      `f ${vCount + a} ${vCount + b} ${vCount + c} ${vCount + d2}\n`;
    out += f(1, 2, 3, 4);
    out += f(5, 6, 7, 8);
    out += f(1, 2, 6, 5);
    out += f(2, 3, 7, 6);
    out += f(3, 4, 8, 7);
    out += f(4, 1, 5, 8);
    vCount += 8;
  };

  // floor slab
  box(plan.width / 2, plan.length / 2, 0, plan.width, plan.length, 0.05);
  // walls
  plan.walls.forEach((w) => {
    const mx = (w.x1 + w.x2) / 2;
    const my = (w.y1 + w.y2) / 2;
    const len = Math.hypot(w.x2 - w.x1, w.y2 - w.y1);
    const horizontal = Math.abs(w.x2 - w.x1) >= Math.abs(w.y2 - w.y1);
    box(mx, my, 0, horizontal ? len : w.thickness, horizontal ? w.thickness : len, plan.wallHeight);
  });
  // furniture
  plan.furniture.forEach((f) => {
    box(f.x, f.y, 0, f.w * f.scale, f.d * f.scale, f.h * f.scale);
  });

  return out;
}
