import { captureRef } from 'react-native-view-shot';
import * as MediaLibrary from 'expo-media-library';
import * as Sharing from 'expo-sharing';
import * as Print from 'expo-print';
// The bare 'expo-file-system' import is the new object-oriented API (File/
// Directory/Paths) — its string-based functions (writeAsStringAsync, etc.) are
// stubs that throw "is deprecated" in SDK 54. This file wants the old
// string-path API, so it comes from the legacy subpath (see assetPaths.js for
// the same pattern elsewhere in the codebase).
import * as FileSystem from 'expo-file-system/legacy';

import { planArea, itemDims } from '@/domain/floorplan';

// Capture a view ref to PNG and save it to the photo library (with permission),
// falling back to the share sheet.
export async function exportPng(viewRef, filename = 'homeplanner') {
  const uri = await captureRef(viewRef, { format: 'png', quality: 1 });
  try {
    const perm = await MediaLibrary.requestPermissionsAsync();
    if (perm.granted) {
      await MediaLibrary.saveToLibraryAsync(uri);
      return { uri, saved: true };
    }
  } catch {
    /* fall through to sharing */
  }
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: 'image/png' });
  }
  return { uri, saved: false, filename };
}

// Build a dimensioned PDF via HTML → print-to-PDF, then share it — one page
// per floor for a multi-floor project, each headed by its own floor name.
// `floors` is [{ name, plan, ref }], `ref` pointing at that floor's own
// PlanRenderer instance (the same component the 2D editor uses) so every page
// is pixel-identical to what the user sees on screen, instead of the old stub
// that only drew a bordered box.
export async function exportPdf(project, floors) {
  const { name } = project;
  const multi = floors.length > 1;
  const pages = [];
  for (const f of floors) {
    // Captured one at a time (not Promise.all) — concurrent native captures
    // of separate offscreen views are unreliable on some Android devices.
    const base64 = await captureRef(f.ref, { format: 'png', quality: 1, result: 'base64' });
    pages.push({ ...f, base64, area: planArea(f.plan) });
  }
  const pageHtml = pages
    .map((p, i) => {
      const heading = multi ? `${name} — Floor ${i + 1}: ${p.name}` : name;
      const pageBreak = i < pages.length - 1 ? 'page-break-after: always;' : '';
      const footer = i === pages.length - 1 ? '<p style="margin-top:32px; color:#9A9488;">Generated by HomePlanner</p>' : '';
      return `
        <div style="${pageBreak}">
          <h1 style="color:#BC5B3A; margin-bottom:4px;">${heading}</h1>
          <p style="color:#57534B; margin-top:0;">Floor plan · ${p.plan.width.toFixed(1)}m × ${p.plan.length.toFixed(1)}m · ${p.area} m²</p>
          <img src="data:image/png;base64,${p.base64}" style="width:100%; max-width:720px; border-radius:12px; margin-top:16px;" />
          ${footer}
        </div>`;
    })
    .join('');
  const html = `<html><body style="font-family: -apple-system, sans-serif; padding:32px; color:#1B1A17;">${pageHtml}</body></html>`;
  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: 'application/pdf' });
  }
  return { uri };
}

// Generate a minimal OBJ (floor + wall boxes + furniture boxes) and share it.
export async function exportObj(project) {
  const obj = buildObj(project.plan);
  const uri = `${FileSystem.cacheDirectory}${project.name.replace(/\s+/g, '_')}.obj`;
  await FileSystem.writeAsStringAsync(uri, obj);
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: 'model/obj' });
  }
  return { uri };
}

// --- OBJ geometry builder -------------------------------------------------
function buildObj(plan) {
  let out = '# HomePlanner export\n';
  let vCount = 0;

  // rotationDeg rotates the box's footprint around (cx, cy) before extruding,
  // so a placed item that's rotated in the 2D plan comes out rotated in the
  // exported mesh too, instead of every box facing the same fixed way.
  const box = (cx, cy, cz, w, d, h, rotationDeg = 0) => {
    const rad = (rotationDeg * Math.PI) / 180;
    const cos = Math.cos(rad);
    const sin = Math.sin(rad);
    const hw = w / 2;
    const hd = d / 2;
    const corners = [
      [-hw, -hd],
      [hw, -hd],
      [hw, hd],
      [-hw, hd],
    ].map(([lx, ly]) => [cx + lx * cos - ly * sin, cy + lx * sin + ly * cos]);
    const y0 = cz;
    const y1 = cz + h;
    const verts = [
      [corners[0][0], y0, corners[0][1]],
      [corners[1][0], y0, corners[1][1]],
      [corners[2][0], y0, corners[2][1]],
      [corners[3][0], y0, corners[3][1]],
      [corners[0][0], y1, corners[0][1]],
      [corners[1][0], y1, corners[1][1]],
      [corners[2][0], y1, corners[2][1]],
      [corners[3][0], y1, corners[3][1]],
    ];
    verts.forEach((v) => {
      out += `v ${v[0].toFixed(3)} ${v[1].toFixed(3)} ${v[2].toFixed(3)}\n`;
    });
    const f = (a, b, c, d2) =>
      `f ${vCount + a} ${vCount + b} ${vCount + c} ${vCount + d2}\n`;
    out += f(1, 2, 3, 4);
    out += f(5, 6, 7, 8);
    out += f(1, 2, 6, 5);
    out += f(2, 3, 7, 6);
    out += f(3, 4, 8, 7);
    out += f(4, 1, 5, 8);
    vCount += 8;
  };

  // floor slab
  box(plan.width / 2, plan.length / 2, 0, plan.width, plan.length, 0.05);
  // walls
  plan.walls.forEach((w) => {
    const mx = (w.x1 + w.x2) / 2;
    const my = (w.y1 + w.y2) / 2;
    const len = Math.hypot(w.x2 - w.x1, w.y2 - w.y1);
    const horizontal = Math.abs(w.x2 - w.x1) >= Math.abs(w.y2 - w.y1);
    box(mx, my, 0, horizontal ? len : w.thickness, horizontal ? w.thickness : len, plan.wallHeight);
  });
  // furniture
  plan.furniture.forEach((f) => {
    const dm = itemDims(f);
    box(f.x, f.y, 0, dm.w, dm.d, dm.h, f.rotation || 0);
  });

  return out;
}
